version: '3.7'
services:
  postgres:
    image: postgres:12
    container_name: postgresprisma
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  nest:
    build: .
    tty: true
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    command: ['yarn', 'start:prod']
    env_file:
      - .env.docker

volumes:
  postgres:
    name: nest-db
